### ISSUE TITLE
Some users received errors while downloading, but some did not have such errors

### ISSUE THREAD

**Issue by jcchouinard05** [mob41/osumer#35]
### My environment

- My operating system:Windows 10

- My Java Version:Java 8 build 261
### About my issue

When i was trying to download a map from a multi the song jsut woulnd do it and osumer just rejected me an error telling it could not be downloades or something Thanks for the help JC
### Dump files

[1597595434784.txt](https://github.com/mob41/osumer/files/5080985/1597595434784.txt)
[1597595434872.txt](https://github.com/mob41/osumer/files/5080986/1597595434872.txt)
[1597595434771.txt](https://github.com/mob41/osumer/files/5080987/1597595434771.txt)

**Comment by a1aw** [comment]
![Capture](https://user-images.githubusercontent.com/12967084/91638920-7aaca800-ea45-11ea-8f4e-713be632d80c.PNG)

In my instance (2.0.0-snapshot-b10), it does not output an error for me. Please check whether your internet connection is properly connected and your location does not block from accessing osu! domains.

**Comment by jcchouinard05** [comment]
when i got in osu mer it just give me the error in osu i will get back home later this evening and see what happens

**Comment by vatei** [comment]
Hi, I have the same issue too.
The dumps seem to be identical to the author's.

**Comment by a1aw** [comment]
May you guys try directly make a download at the user interface? (e.g. ```s320118``` downloads Reol No Title)? I guess there's a session timeout problem causing this, as the website won't show a download link if you are logged out.

**Comment by vatei** [comment]
Hello,
Just tried it and got this.
![image](https://user-images.githubusercontent.com/45978249/96980069-956c3c00-151f-11eb-9a56-4379cc804e76.png)

**Comment by a1aw** [comment]
Can you provide what beatmap you have requested it to download? And have you provided correct osu! credentials in the Preferences?

**Comment by vatei** [comment]
Sure, I used the one you suggested (s320118), and I logged in again just in case. I've tried providing wrong credentials and I get an error message, so I'm pretty sure they are correct.

**Comment by a1aw** [comment]
It sounds weird to me because I can download them correctly.
![Capture](https://user-images.githubusercontent.com/12967084/96989078-c4060900-1557-11eb-9a67-1cb15c97b7d1.PNG)
![Capture2](https://user-images.githubusercontent.com/12967084/96989082-c5373600-1557-11eb-80fa-2d35dea584ad.PNG)

**Comment by a1aw** [comment]
Can you do "Win+R" and navigate to ```%localappdata%\osumerExpress\dumps```? And upload the latest dumps (check the timestamps) the app generated

**Comment by a1aw** [comment]
I have to apologize that the current debug system in the app is pretty bad. I originally want to change it but it still don't have time.

**Comment by vatei** [comment]
Just deleted all the dumps and retried,  generates two files.

```
===!===!===!===!-osumer-debugger-dump-!===!===!===!===
Debug information generated on Fri Oct 23 11:51:14 CEST 2020 (1603446674750 ms)
osumerDebugger v.2.0.0-snapshot-b10
osumer v.2.0.0-snapshot-b10

O/S Name: Windows 10

Current operation: Validate download link element. Throw exception if size() equal to 0
Returned message: No element with class "beatmap_download_link", which should be at least one in a beatmap info page. Invalid beatmap URL?

Last operation: Get elements by class "beatmap_download_link"
Next operation: Get the first element of the download links elements

Data specified: (Contains private data)

Exception stacktrace: 
com.github.mob41.osumer.debug.WithDumpException
	at com.github.mob41.osums.OsumsOldParser.parseSong(OsumsOldParser.java:429)
	at com.github.mob41.osums.OsumsOldParser.getSongInfo(OsumsOldParser.java:306)
	at com.github.mob41.osumer.ui.MainController$13.run(MainController.java:567)

===!===!===!===!-dump-end-!===!===!===!===
```
```
===!===!===!===!-osumer-debugger-dump-!===!===!===!===
Debug information generated on Fri Oct 23 11:51:14 CEST 2020 (1603446674752 ms)
osumerDebugger v.2.0.0-snapshot-b10
osumer v.2.0.0-snapshot-b10

O/S Name: Windows 10

Current operation: Throw debuggable exception on catch
Returned message: Error occurred when getting beatmap info

Last operation: (Try&catch try) getting beatmap info
Next operation: (End of function)

Data specified: https://old.ppy.sh/s/320118

Exception stacktrace: 
com.github.mob41.osumer.debug.WithDumpException: com.github.mob41.osumer.debug.WithDumpException
	at com.github.mob41.osums.OsumsOldParser.getSongInfo(OsumsOldParser.java:308)
	at com.github.mob41.osumer.ui.MainController$13.run(MainController.java:567)
Caused by: com.github.mob41.osumer.debug.WithDumpException
	at com.github.mob41.osums.OsumsOldParser.parseSong(OsumsOldParser.java:429)
	at com.github.mob41.osums.OsumsOldParser.getSongInfo(OsumsOldParser.java:306)
	... 1 more

===!===!===!===!-dump-end-!===!===!===!===
```

**Comment by a1aw** [comment]
My guess is you are still not logged into osu! inside osumer. The download link does not show up if you are logged out. There are multiple reasons causing this:

1. You have not approved your current computer/IP accessing your osu! account. **Try accessing osu! website manually in your browser to try download a random song.**

2. Configuration mismatch in the current instance of app. **Try open osumer, at the toolbar ```File -> Exit and terminate daemon``` and start osumer again after 15 seconds**

3. Hmm... it's weird... I can't think another reasons causing this

**Comment by vatei** [comment]
I'm already logged on my current browser, I tried another one just to be sure but I logged in just fine.
No luck with number two either, still the exact same error

**Comment by lukemagdalin** [comment]
I am also having the same problem, with the same error.
